# Generated by Django 2.2 on 2021-03-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importmaterialmodel',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=19),
        ),
    ]
